DELIMITER //
CREATE FUNCTION quantidade_musicas_no_historico(USER_ID INT)
RETURNS INT READS SQL DATA
BEGIN
DECLARE LISTENED_MUSICS INT;
SELECT
COUNT(*)
FROM
SpotifyClone.musichistory musichistory
WHERE
musichistory.USER_ID = USER_ID
GROUP BY musichistory.USER_ID
INTO LISTENED_MUSICS;
RETURN LISTENED_MUSICS;
END //
